version: 2
updates:
    -   package-ecosystem: composer
        directory: "/"
        open-pull-requests-limit: 20
        schedule:
            interval: daily
            time: "06:00"
            timezone: Europe/Amsterdam
        rebase-strategy: disabled

